
FROM debian:latest

#RUN apt clean
#RUN apt update
#RUN apt upgrade
#RUN apt -y install iproute2 
#RUN apt -y install net-tools 

EXPOSE 5411/tcp
EXPOSE 5412/tcp

WORKDIR /app
COPY . .
ENTRYPOINT ["./service.run"]